services:
  - type: web
    name: chat-server
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8175269064:AAEUBxMk1B3XrxU7OfgcSFOpBy44OzOyNA4
      - key: TELEGRAM_CHAT_ID
        value: -4500008974
      - key: PORT
        value: 3001